[phases.setup]
nixPkgs = ["python312", "curl"]

[phases.install]
cmds = [
  "cd backend && curl -sS https://bootstrap.pypa.io/get-pip.py -o get-pip.py",
  "cd backend && python3 get-pip.py",
  "cd backend && python3 -m pip install --upgrade pip",
  "cd backend && python3 -m pip install -r requirements.txt",
  "cd backend && rm get-pip.py"
]

[phases.build]
cmds = [
  "cd backend && python3 manage.py collectstatic --no-input",
  "cd backend && python3 manage.py migrate"
]

[start]
cmd = "cd backend && gunicorn portfolio_backend.wsgi:application"

