[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = [
  "cd backend && pip install --upgrade pip",
  "cd backend && pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd backend && python manage.py collectstatic --no-input",
  "cd backend && python manage.py migrate"
]

[start]
cmd = "cd backend && gunicorn portfolio_backend.wsgi:application"

