[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = [
  "cd backend && python3 -m pip install --upgrade pip",
  "cd backend && python3 -m pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd backend && python3 manage.py collectstatic --no-input",
  "cd backend && python3 manage.py migrate"
]

[start]
cmd = "cd backend && python3 -m gunicorn portfolio_backend.wsgi:application"

