[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["python3 -m pip install --upgrade pip", "python3 -m pip install -r requirements.txt"]

[phases.build]
cmds = ["python3 manage.py collectstatic --no-input", "python3 manage.py migrate"]

[start]
cmd = "gunicorn portfolio_backend.wsgi:application"

